// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Color: typeof import('./page/demo/color.vue')['default']
    ColorCard: typeof import('./page/demo/colorCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ImageLazy: typeof import('./page/demo/imageLazy.vue')['default']
    Magnify: typeof import('./page/demo/magnify.vue')['default']
    Model: typeof import('./page/demo/model.vue')['default']
    Navigation: typeof import('./page/demo/navigation.vue')['default']
    Password: typeof import('./page/demo/password.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Store: typeof import('./page/demo/store.vue')['default']
  }
}

export {}
